pipeline {
    agent any
    script {
        try {
            nodejs = tool name: 'nodejs-12.16.3'
            env.NODEJS_HOME = "${nodejs}"
            env.PATH = "${env.NODEJS_HOME}/bin:${env.PATH}"

            stage('Clone Repository') {
                git branch: '${BRANCH}', credentialsId: 'Repository_SCM_Credential', url: 'git@github.com:Muhammadimranzamir101/playwrightJs.git'
            }

            stage('NPM install') {
                sh '''
                            npm install
                        '''
            }

            stage('Run Chrome tests') {
                    browserstack(credentialsId: 'Browserstack_credentials', localConfig: [localOptions: '--include-hosts *.*.com, *.*.com*, *.com, *.com* --force-local', localPath: '']) {
                        try {
                        env.BROWSERSTACK_USERNAME = "${BROWSERSTACK_USERNAME}"
                        env.BROWSERSTACK_ACCESS_KEY = "${BROWSERSTACK_ACCESS_KEY}"
                        env.BROWSERSTACK_LOCAL_IDENTIFIER = "${BROWSERSTACK_LOCAL_IDENTIFIER}"

                        sh '''
                                         sh 'npx playwright test --project=chromium --retries=1
                                    '''
                                    } catch (error) {
                        error.printStackTrace()
                        println('Got an error')
                        }
                    }
            }
        }
        catch (error) {
            if (currentBuild.result == null) {
                currentBuild.result = 'FAILURE'   // sets the ordinal as 4 and boolean to false
            }
        }
    }
}

