pipeline {
    agent any
    stages {
        stage('setup') {
            steps {
                browserstack(credentialsId: 'Browserstack_credentials', localConfig: [localOptions: '--include-hosts *.*.com, *.*.com*, *.com, *.com* --force-local', localPath: '']) {
                    // add commands to run test
                    // Following are some of the example commands -----

                    sh 'wget "https://www.browserstack.com/browserstack-local/BrowserStackLocal-darwin-x64.zip"'
                    sh 'unzip BrowserStackLocal-darwin-x64.zip'
                    sh './BrowserStackLocal --key $BROWSERSTACK_ACCESS_KEY --daemon start'
                    sh '<your_test_commands>'
                    sh './BrowserStackLocal --key $BROWSERSTACK_ACCESS_KEY --daemon stop'

                    sh 'npm install'
                    sh 'node single.js'
                    sh 'node parallel.js'
                }
            }
        }
    }
}
