name: Test Reporter

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed

jobs:
  report:
    name: Workflow test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
    - uses: dorny/test-reporter@v1.6.0
      with:
        artifact: test-results
        name: Workflow Report
        path: '*.xml'
        reporter: jest-junit